#!/bin/bash
# Wrapper to let www-data generate certificates

# Override default path before library include: puppet user
# doesn't have write permission on default LOGDIR
LOGDIR="/var/log/puppet"

. $(dirname $(realpath $0))/../lib/bash/softec-common.sh || exit

if [ -z $1 ]; then
    echo "\nSyntax is $0 <hostname>\n"
    log_error "Command call from user '$USERNAME' without valid parameter"
    exit 1
fi

/usr/bin/puppet cert generate $1 | grep -i signed
# se il puppet master è configurato con l'autosign il comando esce con un errore ed exit code 24
# anche se i certificati vengono generati correttamente. Uso come stato di uscita quello del grep su 'Signed'
if [ $? -eq 0 ]; then
    exit 0
else
    log_error "puppet cert generate exit with code $?"
    exit 1
fi
